# Generated by Django 4.0.5 on 2022-07-21 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_managementapp', '0002_addcatagory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
                ('addcatagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint_managementapp.addcatagory')),
            ],
            options={
                'db_table': 'Update_Status',
            },
        ),
    ]
