# Generated by Django 4.0.5 on 2022-07-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_managementapp', '0003_update_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descreption', models.CharField(max_length=100)),
                ('solvers', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Send_Query',
            },
        ),
    ]
