# Generated by Django 4.0.5 on 2022-07-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_managementapp', '0005_query_replay'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Query_Replay',
            new_name='Replay',
        ),
        migrations.AlterModelTable(
            name='replay',
            table='Replay',
        ),
    ]
